# consts.py

drivers = [
    "C:\\Windows\\System32\\drivers\\VBoxMouse.sys",
    "C:\\Windows\\System32\\drivers\\VBoxGuest.sys",
    "C:\\Windows\\System32\\drivers\\VBoxSF.sys",
    "C:\\Windows\\System32\\drivers\\VBoxVideo.sys",
    "C:\\Windows\\System32\\vboxdisp.dll",
    "C:\\Windows\\System32\\vboxhook.dll",
    "C:\\Windows\\System32\\vboxmrxnp.dll",
    "C:\\Windows\\System32\\vboxogl.dll",
    "C:\\Windows\\System32\\vboxoglarrayspu.dll",
    "C:\\Windows\\System32\\vboxservice.exe",
    "C:\\Windows\\System32\\vboxtray.exe",
    "C:\\Windows\\System32\\VBoxControl.exe",
    "C:\\Windows\\System32\\drivers\\vmmouse.sys",
    "C:\\Windows\\System32\\drivers\\vmhgfs.sys",
    "C:\\Windows\\System32\\drivers\\vmci.sys",
    "C:\\Windows\\System32\\drivers\\vmmemctl.sys",
    "C:\\Windows\\System32\\drivers\\vmmouse.sys",
    "C:\\Windows\\System32\\drivers\\vmrawdsk.sys",
    "C:\\Windows\\System32\\drivers\\vmusbmouse.sys",
]

processes = [
    "vboxservice.exe",
    "vboxtray.exe",
    "vmtoolsd.exe",
    "vmwaretray.exe",
    "vmware.exe",
    "vmware-vmx.exe",
    "vmwareuser",
    "VGAuthService.exe",
    "vmacthlp.exe",
    "vmsrvc.exe",
    "vmusrvc.exe",
    "xenservice.exe",
    "qemu-ga.exe",
    "wireshark.exe",
    "Procmon.exe",
    "Procmon64.exe",
    "volatility.exe",
    "volatility3.exe",
    "DumpIt.exe",
    "dumpit.exe",
]

hostnames_list = [
    "Sandbox",
    "SANDBOX",
    "malware",
    "virus",
    "Virus",
    "sample",
    "debug",
    "USER-PC",
    "analysis",
    "cuckoo",
    "cuckoofork",
    "Cuckoo",
]

usernames_list = [
    "sandbox",
    "virus",
    "malware",
    "debug4fun",
    "debug",
    "sys",
    "user1",
    "Virtual",
    "virtual",
    "analysi",
    "trans_iso_0",
    "j.yoroi",
    "venuseye",
    "VenusEye",
    "VirusTotal",
    "virustotal",
]
